// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwUgYnwuw_YEdpUsCyTdBHpPNH8Hf8UBM',
    appId: '1:72397530270:web:f38da708a3388882fdc78f',
    messagingSenderId: '72397530270',
    projectId: 'weddingtest-2000',
    authDomain: 'weddingtest-2000.firebaseapp.com',
    storageBucket: 'weddingtest-2000.firebasestorage.app',
    measurementId: 'G-1GNHVXJRP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk1RL6BoTL_kPCA15-_FWHDKSmXLvpnxc',
    appId: '1:72397530270:android:52d96858c6f612f6fdc78f',
    messagingSenderId: '72397530270',
    projectId: 'weddingtest-2000',
    storageBucket: 'weddingtest-2000.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRxpvB4ySofi9wJ6i6nGQmeHBIWv-jyeY',
    appId: '1:72397530270:ios:0edb7d3460c8123afdc78f',
    messagingSenderId: '72397530270',
    projectId: 'weddingtest-2000',
    storageBucket: 'weddingtest-2000.firebasestorage.app',
    iosBundleId: 'com.example.weddingTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRxpvB4ySofi9wJ6i6nGQmeHBIWv-jyeY',
    appId: '1:72397530270:ios:0edb7d3460c8123afdc78f',
    messagingSenderId: '72397530270',
    projectId: 'weddingtest-2000',
    storageBucket: 'weddingtest-2000.firebasestorage.app',
    iosBundleId: 'com.example.weddingTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwUgYnwuw_YEdpUsCyTdBHpPNH8Hf8UBM',
    appId: '1:72397530270:web:821e03340076e1c3fdc78f',
    messagingSenderId: '72397530270',
    projectId: 'weddingtest-2000',
    authDomain: 'weddingtest-2000.firebaseapp.com',
    storageBucket: 'weddingtest-2000.firebasestorage.app',
    measurementId: 'G-ZEF90Z6J25',
  );
}
